type = "pod"
description = "Alpine Linux Edge"

run-cmd = ["/bin/sleep", "infinity"]
run-writable-file-system = true

[build]
type = "script"
script = """
ADD alpine/alpine-minirootfs-3.15.0_alpha20210804-x86_64.tar.gz /
COPY alpine/apk-repos-edge /etc/apk/repositories
SHELL ["/bin/sh", "-c"]
"""

[storage."/app"]
max-size-mb=5000
type="block"
