type = "pod"
run-cmd = ["/usr/local/bin/docker-entrypoint.sh", "apache2-foreground"]
run-writable-file-system = true

[build]
type = "script"
script = """
FROM wordpress:6-php7.4-apache
RUN cp $PHP_INI_DIR/php.ini-production  $PHP_INI_DIR/php.ini

# max upload size
RUN sed 's|post_max_size = 8M|post_max_size = 1000M|g' -i $PHP_INI_DIR/php.ini
RUN sed 's|upload_max_filesize = 2M|upload_max_filesize = 1000M|g' -i $PHP_INI_DIR/php.ini

# timeout
RUN sed 's|max_execution_time = 30|max_execution_time = 900|g' -i $PHP_INI_DIR/php.ini
RUN sed 's|max_input_time = 60|max_input_time = 900|g' -i $PHP_INI_DIR/php.ini

RUN sed 's|;max_input_vars = 1000|max_input_vars = 10000|g' -i $PHP_INI_DIR/php.ini
RUN sed 's|memory_limit = 128M|memory_limit = 256M|g' -i $PHP_INI_DIR/php.ini

# ionCube Loader for PHP
RUN sed 's|extension=xsl|extension=xsl\\nzend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20190902/ioncube_loader_lin_7.4.so|g' -i $PHP_INI_DIR/php.ini
ADD wordpress/ioncube_loader_lin_7.4.so  /usr/local/lib/php/extensions/no-debug-non-zts-20190902

# soap
RUN apt update && apt install -y libxml2-dev
RUN docker-php-ext-install soap

# tools
ADD wordpress/tools  /var/www/tools

# locales
RUN apt install -y locales
RUN echo "LC_ALL=pl_PL.UTF-8" > /etc/environment
RUN echo "pl_PL.UTF-8 UTF-8" > /etc/locale.gen
RUN echo "LANG=pl_PL.UTF-8" > /etc/locale.conf
RUN locale-gen pl_PL.UTF-8 && update-locale
RUN DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales
RUN sed 's|;intl.default_locale =|intl.default_locale = pl_PL.UTF-8|g' -i $PHP_INI_DIR/php.ini

# datadog
#RUN cd /tmp && \
#    curl -LO https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-setup.php && \
#    php datadog-setup.php --php-bin=all --enable-appsec --enable-profiling && \
#    php datadog-setup.php config set --php-bin all -ddatadog.profiling.experimental_timeline_enabled=1

# proxysql
RUN apt-get update && apt-get install -y --no-install-recommends lsb-release wget apt-transport-https ca-certificates
RUN wget -nv -O /etc/apt/trusted.gpg.d/proxysql-2.4.x-keyring.gpg 'https://repo.proxysql.com/ProxySQL/proxysql-2.4.x/repo_pub_key.gpg'
RUN echo "deb https://repo.proxysql.com/ProxySQL/proxysql-2.4.x/$(lsb_release -sc)/ ./" | tee /etc/apt/sources.list.d/proxysql.list
RUN apt update
RUN apt install -y proxysql

# run
ADD wordpress/docker-entrypoint.sh  /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh 
"""

[variables]
WORDPRESS_DB_HOST = "mariadb"
WORDPRESS_DB_USER = "{{mariadb.MARIADB_USER}}"
WORDPRESS_DB_NAME = "{{mariadb.MARIADB_DATABASE}}"
WORDPRESS_TABLE_PREFIX = "wp_"
WORDPRESS_DB_PASSWORD.secret = true
WORDPRESS_DB_PASSWORD.value = "{{mariadb.MARIADB_PASSWORD}}"
LANG = "pl_PL.UTF-8"
LC_ALL = "pl_PL.UTF-8"
LC_CTYPE = "pl_PL.UTF-8"
LANGUAGE = "pl_PL"

[storage."/var/www/html"]
type = "block"
max-size-mb = 12000
name = "wordpress"

[expose.80]
type = "http"
probe.disable = true
